version: '3.7'
services:
  database:
    image: 'mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - '3308:3306'
    networks:
      - grafana_network

networks:
  grafana_network:
    external: false
    name: grafana_network

